# This function showcases how one might write a function to be used as an
# RStudio project template. This function will be called when the user invokes
# the New Project wizard using the project template defined in the template file
# at:
#
#   inst/rstudio/templates/project/epiR_project.dcf
#
# The function itself just echos its inputs and outputs to a file called INDEX,
# which is then opened by RStudio when the new project is opened.
epiR_project <- function(path, ...) {

  # ensure path exists
  dir.create(path, recursive = TRUE, showWarnings = FALSE)

  # setup folder structure
  dir.create("analysis/src", recursive = TRUE)
  dir.create("communication/internal_comm", recursive = TRUE)
  dir.create("communication/journal_comm", recursive = TRUE)
  dir.create("data/data_clean", recursive = TRUE)
  dir.create("data/data_raw", recursive = TRUE)
  dir.create("dissemination/manuscripts", recursive = TRUE)
  dir.create("dissemination/posters", recursive = TRUE)
  dir.create("dissemination/presentations", recursive = TRUE)
  dir.create("documentation", recursive = TRUE)
  dir.create("misc", recursive = TRUE)

  # generate header
  header <- c(
    "---"
    )

  # collect inputs
  dots <- list(...)
  yaml <- lapply(seq_along(dots), function(i) {
    key <- names(dots)[[i]]
    val <- dots[[i]]
    paste0(key, ": ", val)
  })

  header_2 <- c(
    "format: html",
    "editor: visual",
    paste("date: ",ymd(today())),
    "---",
    "",
    "# Quarto Analysis",
    " This file was generated by a call to 'epiR::epiR_project()'.",
    " The following inputs were received:",
    ""
  )

  # collect into single text string
  contents <- paste(
    paste(header, collapse = "\n"),
    paste(yaml, collapse = "\n"),
    paste(header_2, collapse = "\n"),
    sep = "\n"
  )
  library(lubridate)
  # write to index file
  writeLines(contents, con = file.path(path, paste(ymd(today()),"_analysis.qmd")))

}
