# This function showcases how one might write a function to be used as an
# RStudio project template. This function will be called when the user invokes
# the New Project wizard using the project template defined in the template file
# at:
#
#   inst/rstudio/templates/project/epiR_project.dcf
#
# The function itself just echos its inputs and outputs to a file called INDEX,
# which is then opened by RStudio when the new project is opened.
library(lubridate)
library(here)

#here::i_am("epiR_project.R")

epiR_project <- function(path, ...) {

  # ensure path exists
  dir.create(path, recursive = TRUE, showWarnings = FALSE)
  print(path)

  here::i_am(path)

  # setup folder structure
  dir.create(here("analysis","src"), recursive = TRUE)
  dir.create(here("communication","internal_comm"), recursive = TRUE)
  dir.create(here("communication","journal_comm"), recursive = TRUE)
  dir.create(here("data","data_clean"), recursive = TRUE)
  dir.create(here("data","data_raw"), recursive = TRUE)
  dir.create(here("dissemination","manuscripts"), recursive = TRUE)
  #dir.create(here("dissemination","posters"), recursive = TRUE)
  dir.create(here("dissemination","presentations"), recursive = TRUE)
  dir.create(here("documentation"), recursive = TRUE)
  dir.create(here("misc"), recursive = TRUE)

  # generate header
  header <- c(
    "---"
    )

  # collect inputs
  dots <- list(...)
  yaml <- lapply(seq_along(dots), function(i) {
    key <- names(dots)[[i]]
    val <- dots[[i]]
    paste0(key, ": ", val)
  })

  header_2 <- c(
    "format: html",
    "editor: visual",
    paste("date: ",lubridate::ymd(today())),
    "---",
    "",
    "# Quarto Analysis",
    " This file was generated by a call to 'epiR::epiR_project()'.",
    " The following inputs were received:",
    ""
  )

  # collect into single text string
  contents <- paste(
    paste(header, collapse = "\n"),
    paste(yaml, collapse = "\n"),
    paste(header_2, collapse = "\n"),
    sep = "\n"
  )

  # write to index file
  writeLines(contents, con = file.path(path, paste(lubridate::ymd(today()),"_analysis.qmd", sep = "")))

}
